baseURL: ''
languageCode: en-us
title: Personal website and blog
theme: hugo refresh
DefaultContentLanguage: en
disableKinds:
  - sitemap
  - RSS
blackfriday:
  hrefTargetBlank: true
Taxonomies:
  tag: tags
params:
  articlesPerRow: 3
  favicon: /images/favicon.svg
  jsMinify: false
  cssMinify: false
  cssIntegrity: true
  jsIntegrity: true
  mainColour: '#F39200'
  summary:
    defaultImage: /images/default_summary.jpg
  loading:
    image: /images/loaders/rings.svg
  mainPage:
    fontFamily: Open Sans
  sidebar:
    logo: /images/refresh-square.svg
    fontFamily: Open Sans
  navbar:
    fontFamily: Open Sans
    showIcons: false
  pagNotFound:
    image: /images/avataaars_404.png
    title: '404 Page Not Found :('
    subtitle: This is not the page you were looking for...
    imageWidth: 500px
  homepage:
    title: Julia The White
    subtitle: Personal website and blog
    image: /images/avataaars.png
    imageWidth: 500px
  footer:
    logo: /images/refresh-square.svg
    email:
      link: name.surname@domain.com
      title: My Email
    linkedin:
      link: your_linkedin_profile
      title: My LinkedIn
    copyright: Julia The White - 2020
languages:
  en:
    languageName: English
    weight: 1
  ru:
    languageName: Russian
    weight: 2
    params:
      homepage:
        title: Julia белая краска
        subtitle: Персональный сайт и блог
        image: /images/avataaars.png
        imageWidth: 500px
      footer:
        logo: /images/refresh-square.svg
        email:
          link: имя.фамилия@домен.com
          title: Эл. адрес
        linkedin:
          link: your_linkedin_profile
          title: LinkedIn
        copyright: Julia белая краска - 2020
themesDir: themes
publishDir: public
